name: 'Tidal Tools Code Analysis'
description: 'Run tidal'
inputs:
  tidal-email:  # id of input
    description: 'The email for the Tidal Accelerator service user'
    required: true
  tidal-password:
    description: 'The password for the Tidal Accelerator service user'
    required: true
  tidal-url:
    description: 'The workspace for url for your Tidal Accelerator Account ex: https://workspace.tidal.cloud'
    required: true
  app-id:
    description: 'The ID of the application that is linked to this repository'
    required: true
  directory:
   description: 'The directory for tidal-tools to run code analysis on'
   required: true
   default: '${{ github.workspace }}'
runs:
  using: 'docker'
  image: 'docker://gcr.io/tidal-1529434400027/tidal-tools:latest'
  args:
    - --tidal-email
    - '${{ inputs.tidal-email }}'
    - --tidal-password
    - '${{ inputs.tidal-password }}'
    - --tidal-url
    - '${{ inputs.tidal-url }}'
    - analyze
    - code
    - --app-id
    - '${{ inputs.app-id }}'
    - '${{ inputs.directory }}'
