name: 'Tidal Tools Code Analysis'
description: 'Run tidal'
inputs:
  tidal-email:  # id of input
    description: 'Who to greet'
    required: true
  tidal-password:
    description: 'Who to greet'
    required: true
  tidal-url:
    description: 'Who to greet'
    required: true
runs:
  using: 'docker'
  image: 'gcr.io/tidal-1529434400027/tidal-tools:latest'
  args:
    - 'ping'
    - '--tidal-email'
    - '${{inputs.tidal-email}}'
    - '--tidal-password'
    - '${{inputs.tidal-password}}'
    - '--tidal-url'
    - '${{inputs.tidal-url}}'

