on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say validate the action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tidal Doctor action step
        uses: ./ # Uses an action in the root directory
        with:
          tidal-email: '${{ secrets.TIDAL_EMAIL }}'
          tidal-url: '${{ secrets.TIDAL_URL }}'
          tidal-password: '${{ secrets.TIDAL_PASSWORD }}'
        id: hello
