on: [push]

jobs:
  doctor:
    runs-on: ubuntu-latest
    name: A job to run tidal doctor
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tidal Doctor action step
        uses: ./doctor
        with:
          tidal-email: '${{ secrets.TIDAL_EMAIL }}'
          tidal-url: '${{ secrets.TIDAL_URL }}'
          tidal-password: '${{ secrets.TIDAL_PASSWORD }}'
  ping:
    runs-on: ubuntu-latest
    name: A job to run tidal ping
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tidal Ping action step
        uses: ./ping
        with:
          tidal-email: '${{ secrets.TIDAL_EMAIL }}'
          tidal-url: '${{ secrets.TIDAL_URL }}'
          tidal-password: '${{ secrets.TIDAL_PASSWORD }}'
  analyze-code:
    runs-on: ubuntu-latest
    name: A job to validate analyze code
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tidal Code Analyze action step
        uses: ./ # Uses an action in the root directory
        with:
          tidal-email: '${{ secrets.TIDAL_EMAIL }}'
          tidal-url: '${{ secrets.TIDAL_URL }}'
          tidal-password: '${{ secrets.TIDAL_PASSWORD }}'
          app-id: '66'
